test = {   'name': 'q3_3',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> callable(numerical_rating)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> numerical_rating('LQ_CLOSE') == 1\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> numerical_rating('LQ_EDIT') == 2\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> numerical_rating('HQ') == 3\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
